name: receive presence
favicon: null
layout_spectrum: 0.6922722582239658
typography_spectrum: 0.5566485172603279
title: Receive Presence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' UA-75446610-2'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8a8a8a'
    - '#008ff5'
    - '#ababab'
    - '#224f70'
  brandStrength: 1
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.9137579675298184
purpose: []
